# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/managing-repository-settings-with-github-app-and-probot-settings
repository:
  # The name of the repository. Changing this will rename the repository
  name: gitlab-fetches

  # A short description of the repository that will show up on GitHub
  description: A shell script to fetch artifacts from GitLab CI/CD pipelines.

  # A link where more about this repository can be found
  homepage: https://github.com/Addono/gitlab-fetches

  # A comma-separated list of topics to set on the repository
  topics: gitlab, ci-cd, artifacts, shell-script, automation

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to delete head branches when pull requests are merged, or `false`
  delete_branch_on_merge: true

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
    description: Something isn't working as expected
  - name: dependencies
    color: 0366d6
    description: Updates to dependencies
  - name: docker
    color: 2088FF
    description: Changes to Docker configuration
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: 84b6eb
    description: New feature or request
  - name: "github actions"
    color: "2088FF"
    description: "Changes to GitHub Actions workflows"
