name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Build the test Docker image
        run: docker build --no-cache --target test-env --tag gitlab-fetches-test .

      - name: Run the tests
        env:
          GITLAB_E2E_TOKEN: ${{ secrets.GITLAB_E2E_TOKEN }}
        run: docker run --rm -e GITLAB_E2E_TOKEN gitlab-fetches-test

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - test
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release
    
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/v') && github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "repository_lc=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo_name.outputs.repository_lc }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ steps.repo_name.outputs.repository_lc }}:latest
